[project]
name = "nba-scores"
version = "0.1.7"
authors = [
  { name="Christian Cleberg", email="hello@cmc.pub" },
]
description = "A CLI interface to get current NBA scores and standings."
readme = "README.md"
requires-python = ">=3.9"
license = "GPL-3.0-or-later"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "nba_api",
    "tabulate",
    "argparse",
    "textual>=0.89.1,<7.0"
]

[project.urls]
Homepage = "https://git.cleberg.net/nba-scores.git"
Issues = "https://git.cleberg.net/nba-scores.git"

[project.scripts]
nba = "nba.cli:nba"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.uv]
package = true

[tool.setuptools.packages.find]
where = ["."]
include = ["nba*"]

[tool.setuptools.package-data]
"nba.tui" = ["*.tcss"]
